import { useEffect, useState } from "react"
import { MessageSquarePlus, Send } from "lucide-react"
import SectionSkeleton from "../../components/ui/SectionSkeleton"
import { fetchTeacherFeedbackMock } from "../../data/teacherMockData"

export default function TeacherFeedbackPage() {
  const [loading, setLoading] = useState(true)
  const [rows, setRows] = useState([])
  const [notes, setNotes] = useState({})

  useEffect(() => {
    let c = false
    ;(async () => {
      const d = await fetchTeacherFeedbackMock()
      if (!c) {
        setRows(d)
        setLoading(false)
      }
    })()
    return () => {
      c = true
    }
  }, [])

  if (loading) {
    return (
      <div className="min-w-0 max-w-full">
        <SectionSkeleton rows={4} />
      </div>
    )
  }

  return (
    <div className="min-w-0 max-w-full space-y-6">
      <div>
        <h1 className="text-xl font-semibold text-[#151d3a] sm:text-2xl">Feedback</h1>
        <p className="mt-1 text-sm text-[#7d86a5]">Auto-generated insights plus manual teacher notes</p>
      </div>

      <div className="space-y-4">
        {rows.map((r) => (
          <article key={r.id} className="rounded-2xl border border-[#e7eaf3] bg-white p-5 shadow-sm">
            <div className="flex flex-wrap items-start justify-between gap-2">
              <div>
                <p className="font-semibold text-[#151d3a]">{r.student}</p>
                <p className="text-xs text-[#7f88a6]">{r.exam}</p>
              </div>
              <span className="rounded-full bg-[#f4f6fb] px-2.5 py-0.5 text-xs font-semibold capitalize text-[#313a58]">{r.status}</span>
            </div>
            <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-3">
              <div className="rounded-xl bg-[#f6fdf9] p-3 text-sm">
                <p className="text-xs font-semibold uppercase text-[#1f9d67]">Strengths</p>
                <p className="mt-1 text-[#5d6580]">{r.strengths} focus areas highlighted</p>
              </div>
              <div className="rounded-xl bg-[#fffbf4] p-3 text-sm">
                <p className="text-xs font-semibold uppercase text-[#c89422]">Weaknesses</p>
                <p className="mt-1 text-[#5d6580]">{r.weaknesses} improvement areas</p>
              </div>
              <div className="rounded-xl bg-[#eeebff] p-3 text-sm">
                <p className="text-xs font-semibold uppercase text-[#5f4ce6]">Recommendations</p>
                <p className="mt-1 text-[#5d6580]">Generated by AI rubric (mock)</p>
              </div>
            </div>
            <label className="mt-4 block text-sm">
              <span className="flex items-center gap-1 font-medium text-[#151d3a]">
                <MessageSquarePlus className="h-4 w-4 text-[#6562f1]" />
                Manual notes
              </span>
              <textarea
                className="mt-2 w-full rounded-xl border border-[#e3e6ef] px-3 py-2 text-sm"
                rows={2}
                placeholder="Suggestions, encouragement, or corrections…"
                value={notes[r.id] ?? ""}
                onChange={(e) => setNotes((prev) => ({ ...prev, [r.id]: e.target.value }))}
              />
            </label>
            <button
              type="button"
              className="mt-3 inline-flex h-10 items-center gap-2 rounded-xl bg-[#6562f1] px-4 text-sm font-semibold text-white"
              onClick={() => alert("Demo: feedback published to student")}
            >
              <Send className="h-4 w-4" />
              Publish to student
            </button>
          </article>
        ))}
      </div>
    </div>
  )
}
